BLOG2SHARE/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views


urlpatterns = [
	path('admin/', admin.site.urls),
	path('',include('accounts.urls')),
	path('articles/',include('articles.urls')),
	path('about/',views.about),
	path('',article_views.article_list,name = "home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .import views


app_name="accounts"


urlpatterns = [
path('accounts/signup/',views.signup_view,name = "signup"),
path('accounts/login/',views.login_view,name = "login"),
path('accounts/logout/',views.logout_view,name = "logout"),
]

articles/urls.py
from .import views
from django.urls import path

app_name='articles'

urlpatterns = [
	path('',views.article_list,name = "list"),
	path('create/',views.article_create,name = "create"),
	path('<slug>/',views.article_detail,name = "detail"),
	]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
class Article(models.Model):
	title = models.CharField(max_length = 100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add = True)
	photo = models.ImageField(default="default.png",null=True,blank=True)
	author = models.ForeignKey(User,on_delete=models.PROTECT,default=None)




	def __str__(self):
		return self.title


	def snippet(self):
		return self.body[:50]+"..."

articles/forms.py
from django import forms
from .import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','photo']

BLOG2SHARE/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
	#return HttpResponse('homepage')
	return render(request,'homepage.html')

def about(request):
	#return HttpResponse('about')
	return render(request,'about.html')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})


def login_view(request):

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in user
            user = form.get_user()
            login(request,user)
            if'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms


def article_list(request):
	articles = Article.objects.all().order_by('date')
	return render(request,'articles/article_list.html',{'articles':articles})


def article_detail(request,slug):
	#return HttpResponse(slug)
	article = Article.objects.get(slug=slug)
	return render(request,'articles/article_detail.html',{'article':article})

@login_required(login_url="/accounts/login/")

def article_create(request):
	if request.method == 'POST':
		form  = forms.CreateArticle(request.POST,request.FILES)
		if form.is_valid():  
			instance = form.save(commit = False)
			instance.author = request.user
			instance.save()
			return redirect('articles:list')
	form = forms.CreateArticle()
	return render(request,'articles/article_create.html',{'form':form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<style media="screen">
  #id_username{
    width: 100%;
  }
  #id_password{
    width: 100%;
  }
  button{
    padding: : 1em;
  }
</style>
<h1 style="font-size:2em">LOGIN</h1>
<hr>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %}
  {{form}}
  {% if request.GET.next %}
  <br>
  <input type="hidden" name="next" value="{{request.GET.next}}"> <br>
  {% endif %}
  <br>
  <br>
  <button type="submit" value="="Login">LOGIN</button>

</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<style media="screen">
  span .helptext{
    width: 100%;
  }
  label{
    width: 100%;
  }
  #id_username, #id_password1, #id_password2{
    width: 100%;
  }
</style>
<h1>SIGN UP</h1>
<hr>
<form class="site-form" action="/accounts/signup/" method="post">
  {% csrf_token %}
  {{form}}
  <br>
  <button type="submit" value="="Signup">SIGNUP</button>
</form>
{% endblock %}

articles/templates/articles/article_create.html
{%  extends 'base_layout.html' %}

{% block content %}
<div class = "create-article">

  <style media="screen">
    #id_title{
      width: 100%;
    }
    label{
      width: 100%;
    }
    #id_thumbnail{
      width: 100%;
    }
  </style>

  <h2>CREATE A AWESOME NEW ARTICLE!!!</h2>

  <br>
  <form class="site-form" action="{% url 'articles:create' %}"  method="post" enctype="multipart/form-data">
{% csrf_token %}
    {{form}}

    <input type="submit" value="CREATE">

  </form>

</div>


{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}

<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">

<div class="container">

  <div class="article_detail">

    <div class="article">
      <img src="{{article.photo.url}}"/>
      <h2>{{article.title}}</h2>
      <p>{{article.body}}</p>
      <p>{{article.date}}</p>
    </div>
  </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
 {% extends "base_layout.html" %}


{% block content %}

<style>
.article{
  border: 2px solid red;
  margin-bottom: 1.5em;
  padding: 1em;
  border-radius: 10px;
  box-shadow: 5px 10px grey;
}
</style>

<h1 style="font-family: 'Open Sans Condensed', sans-serif;">ARTICLE LIST</h1>
<hr>
<div class="articles">
{% for article in articles %}
<div class="article">
<h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>


<p>{{article.snippet}}</p>
<p>{{article.date}}</p>
<p class="author">POSTED BY {{article.author.username}}</p>

</div>
{% endfor %}
</div>

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>ABOUT</title>
</head>
<body>
<h1>ABOUT US</h1>
<p>WE LOVE SHARING AND INTERACTING FOR KNOWLEGDE</p>
</body>
</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="{% static 'css/blogstyle.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link href="https://fonts.googleapis.com/css?family=Acme|BenchNine|Cairo|Economica|Fjalla+One|Neuton|Ubuntu+Condensed" rel="stylesheet">
<style media="screen">
body{
//  font-family: 'Fjalla One', sans-serif;
  font-size: 1.7em;

font-family: 'Ubuntu Condensed', sans-serif;
background: linear-gradient(to right,lightblue,lightgreen);

}
.logo img{
  width: 10%;

}
a{
  color: red;
  text-decoration: none;
}

</style>



</head>
<body>

  <header class="wrapper">
    <h1><a class="logo" href="{% url 'home'%}"><img src="{% static 'img/logo.png' %}" alt="BLOG2SHARE"/></a></h1>
    <h1><a herf="{% url 'articles:list' %}"></a></h1>



    <nav>
      <ul class="nav justify-content-end">

        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link active" href= "{% url 'articles:create' %}" class="highlight">Create New Article</a></li>

        <li class="nav-item">
          <form class="logout-link" action="{% url 'accounts:logout'%}" method="post">
            {% csrf_token %}
            <button class="nav-link" type="submit">Logout</button>
          </form>
        </li>


        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a></li>
        {% endif %}
      </ul>


    </nav>


  </header>
<div class="container">
  <div class="row">
    <div class="col col-12">

    </div>

    <div class="col co-12">
    </div>
  </div>
</div>
  <div class="row">
    <div class="col col-4"></div>
    <div class="col col-4"><div class="wrapper-101">
      {% block content %}
      {% endblock %}
      </div>
    </div>
    <div class="col col-4">

    </div>
  </div>
</div>

<script>
function pop_me_up(){
  alert("This is who we are.");
}
</script>

</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>HOMEPAGE</title>
</head>
<body>
<h1>THIS IS THE HOMEPAGE</h1>
<p>WELCOME TO BLOG2SHARE WEBSITE</p>
</body>
</html>